# Generated by Django 4.2.5 on 2023-11-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_product_pay_alter_product_photo'),
        ('ShoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
