# Generated by Django 4.2.5 on 2023-11-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0002_remove_shoppingcart_product_shoppingcartproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='shoppingCart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.shoppingcart'),
        ),
    ]
