# Generated by Django 4.2.5 on 2023-10-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='card_data',
            field=models.TextField(null=True),
        ),
    ]
