# Generated by Django 4.2.5 on 2023-11-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0002_rename_product_purchases_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='quantity',
            new_name='amount',
        ),
    ]
