# Generated by Django 4.2.5 on 2023-10-02 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0002_purchases_card_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='purchases_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
