# Generated by Django 4.2.5 on 2023-10-10 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_category_name_alter_label_name_and_more'),
        ('Purchases', '0004_purchaseproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='destination_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='purchases',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Purchases.purchases'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchases',
            name='product',
            field=models.ManyToManyField(through='Purchases.PurchaseProduct', to='Product.product'),
        ),
    ]
