# Generated by Django 4.2.5 on 2023-10-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0005_purchaseproduct_destination_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='card_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
