# Generated by Django 4.2.5 on 2023-10-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0006_alter_purchases_card_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='destination_mail',
            field=models.EmailField(blank=True, default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
