# Generated by Django 4.2.5 on 2023-10-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0007_alter_purchaseproduct_destination_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='destination_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
