# Generated by Django 4.2.5 on 2023-10-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0008_alter_purchaseproduct_destination_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
