# Generated by Django 4.2.5 on 2023-10-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0009_alter_purchaseproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
