# Generated by Django 4.2.5 on 2023-11-03 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Purchases', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='puschases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchases.purchases'),
        ),
        migrations.AddField(
            model_name='mail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
        migrations.AddField(
            model_name='mail',
            name='puschases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchases.purchases'),
        ),
        migrations.AddField(
            model_name='key',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
        migrations.AddField(
            model_name='key',
            name='puschases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchases.purchases'),
        ),
    ]
