# Generated by Django 4.2.5 on 2023-10-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.ManyToManyField(to='Product.label'),
        ),
    ]
