# Generated by Django 4.2.5 on 2023-11-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='imgs/'),
        ),
    ]
