# Generated by Django 4.2.5 on 2023-10-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_label_product_product_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.ManyToManyField(null=True, to='Product.label'),
        ),
    ]
