# Generated by Django 4.2.5 on 2023-11-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_description_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pay',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='static/product/default.jpg', upload_to='static/product/'),
        ),
    ]
