# Generated by Django 4.2.5 on 2023-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_key_puschases_remove_mail_puschases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mail',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
