# Generated by Django 4.2.5 on 2023-10-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
