# Generated by Django 4.2.5 on 2023-11-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_key_key_alter_mail_mail_alter_mail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='others',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
