# Generated by Django 4.2.5 on 2023-10-10 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0007_alter_product_price_alter_product_sales_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, to='Product.label'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='Product.product'),
        ),
    ]
